[package]
name = "vidya_interp"
version = "0.1.0"
edition = "2021"
description = "A small crate that adds simple Transform interpolation logic."

[dependencies]
bevy_app = "0.8.0"
bevy_transform = "0.8.0"
bevy_ecs = "0.8.0"
bevy_time = "0.8.0"

[dev-dependencies]
bevy = "0.8.0"